name: "Test"
on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: "macos-latest"
    steps:
    - uses: actions/checkout@v4
    - uses: swift-actions/setup-swift@v1
    - name: Run swift tests
      run: swift test